/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mshri.securefileio;

import java.util.ArrayList;
import java.util.List;

public class App {
    public static void main(String[] args) {
        String fileName = "testfile.txt";
        String path = "C:\\Users\\mshri\\Desktop\\pgp-java-bc\\iofiles\\";
        String plainFile = path + fileName;
        String encFile = path + fileName + ".gpg";
        String encFile2 = path + fileName + "2.gpg";
        String decFile = path + fileName + ".orig";
        String secretKeyPath = path + "testone-secret-key.gpg";
        String publicKeyPath = path + "testone-public-key.gpg";
    
        SecureIO.encryptFile(plainFile, encFile, publicKeyPath);
        SecureIO.decryptFile(encFile, decFile, secretKeyPath, "qwerty12345");

        try {
            List<String> strList = new ArrayList<String>();
            strList = SecureIO.readSecureFileAsStrList(encFile, secretKeyPath, "Nothing");
            for (String item : strList) {
                System.out.println(item);
            }
            SecureIO.writeStrListToSecureFile(encFile2, publicKeyPath, strList);
        } catch (Exception e) {
            System.out.println("ERROR: " + e.getMessage());
        }
    }
}
